

server:
  port: 8091
  error:
    include-message: always
    include-binding-errors: always


spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:~/data/bdpru;
    driver-class-name: org.h2.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m&n"


  #datasource=jdbc:h2:~/data/bdpru
  #spring.datasource.driver-class-name=org.h2.Driver
  #spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
  #spring.h2.console.enabled=true
  #spring.jpa.defer-datasource-initialization=true*
